services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: easykrut
      POSTGRES_PASSWORD: easykrut
      POSTGRES_DB: easykrut
    volumes:
      - easykrut_pg:/var/lib/postgresql/data

volumes:
  easykrut_pg:
